version: '1.0.{build}'

image: Visual Studio 2017
shallow_clone: true

branches:
  only:
  - master

environment:
  matrix:
    - PYTHON: "C:\\Python36"
      PYTHON_VERSION: "3.6.3"
      PYTHON_ARCH: "32"
      APPVEYOR: "true"

init:
  - cmd: git config --global core.autocrlf true
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - python -m pip install -U pip
  - pip install -r requirements-dev.txt

build_script:
  - python setup.py build

test_script:
  - echo "FIXME: insert unit tests"

after_test:
  # if tests are successful, create binary packages
  - python setup.py bdist_wheel
  - python setup.py bdist_wininst
  - python setup.py bdist_msi
  - ps: "ls dist"

# C:\Users\crossbar\Documents\GitHub\crossbario\crossbar-shell>pyinstaller --onefile --clean --name cbsh --hidden-import "cookiecutter.extensions" --hidden-import "jinja2_time" --hidden-import "sphinx.util.compat" --hidden-import "sphinxcontrib.xbr" cbsh/cli.py

#artifacts:
#  # Archive the generated packages in the ci.appveyor.com build report.
#  - path: dist\*

#on_success:
#  - TODO: upload the content of dist/*.whl to a public wheelhouse
#
