version: '1.0.{build}'

image: Visual Studio 2017
shallow_clone: true

branches:
  only:
  - master

environment:
  matrix:
    - PYTHON: "C:\\Python36"
      PYTHON_VERSION: "3.6.3"
      PYTHON_ARCH: "32"
      APPVEYOR: "true"

# rgd chcp 65001: needed for cbor and pyyaml, because of this
# https://github.com/pypa/pip/issues/4251
init:
  - cmd: git config --global core.autocrlf true
  - ps: chcp 65001
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - python -m pip install -U pip
  - pip install -r requirements-dev.txt

build_script:
  - pip install .
  - ps: "(Get-Content .\\cbsh\\_version.py).replace('00000', '{build}') | Set-Content .\\cbsh\\_version.py"

test_script:
  - echo "FIXME: insert unit tests"

after_test:
  # if tests are successful ...

  # patch pip because of issue with namespace packages. otherwise pip
  # and setuptools become unusable later. we need to patch this file:
  #   C:\\Python36\\lib\\site-packages\\pkg_resources\\__init__.py
  # and replace
  #   orig_path.sort(key=position_in_sys_path)
  # with
  #   orig_path = sorted(orig_path, key=position_in_sys_path)
  - ps: "(Get-Content C:\\Python36\\lib\\site-packages\\pkg_resources\\__init__.py).replace('orig_path.sort(key=position_in_sys_path)', 'orig_path = sorted(orig_path, key=position_in_sys_path)') | Set-Content C:\\Python36\\lib\\site-packages\\pkg_resources\\__init__.py"
  
  # create Python binary packages
  - python setup.py sdist
  - python setup.py bdist_wheel --universal
  - python setup.py bdist_wheel
  - python setup.py bdist_wininst
  - python setup.py bdist_msi
  - ps: "ls dist"

  # create one-file executable using pyinstaller
  #
  # note: the warning messages during the build that refer to "api-ms-win-crt-*" as in
  # WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of c:\python36\python.exe
  # appear to be harmless - the generated EXE seems to be fine (roughly 30MB)
  - pyinstaller --onefile --clean --name cbsh --hidden-import "cookiecutter.extensions" --hidden-import "jinja2_time" --hidden-import "sphinx.util.compat" --hidden-import "sphinxcontrib.xbr" cbsh/cli.py
  - ps: "ls dist"
  - cmd: dist\cbsh.exe version

# this step uploads cbsh.exe to
# https://s3.eu-central-1.amazonaws.com/download.crossbario.com/cbsh/windows/dist/cbsh.exe
#
# to generate the encrypted key material for S3 IAM access below, go to:
# https://ci.appveyor.com/tools/encrypt
#
deploy:
  provider: S3
  access_key_id:
    secure: O8zpApNyYa9l577lVw5YzaYALUtZhY06CHkRQZQxOm8=
  secret_access_key:
    secure: 12lctYLle9L+rP2ZohkSKXa4h9IiI0b8YwRlNTtb02h0J8FoQGjVI9scem3GRpCG
  bucket: download.crossbario.com
  region: eu-central-1
  unzip: false
  set_public: true
  folder: cbsh/windows
  artifact: Crossbar.io Shell
