version: '1.0.{build}'

image: Visual Studio 2017
shallow_clone: true

branches:
  only:
  - master

environment:
  matrix:
    - PYTHON: "C:\\Python36"
      PYTHON_VERSION: "3.6.3"
      PYTHON_ARCH: "32"
      APPVEYOR: "true"

init:
  - cmd: git config --global core.autocrlf true
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - python -m pip install -U pip
  - pip install -r requirements-dev.txt

build_script:
  - pip install .

test_script:
  - echo "FIXME: insert unit tests"

after_test:
  # if tests are successful ...

  # patch pip because of issue with namespace packages. otherwise pip
  # and setuptools become unusable later. we need to patch this file:
  #   C:\Python36\lib\site-packages\pkg_resources\__init__.py
  # and replace
  #   orig_path.sort(key=position_in_sys_path)
  # with
  #   orig_path = sorted(orig_path, key=position_in_sys_path)
  - ps: "(Get-Content C:\Python36\lib\site-packages\pkg_resources\__init__.py).replace('orig_path.sort(key=position_in_sys_path)', 'orig_path = sorted(orig_path, key=position_in_sys_path)') | Set-Content C:\Python36\lib\site-packages\pkg_resources\__init__.py"
  
  # create Python binary packages
  - python setup.py sdist
  - python setup.py bdist_wheel --universal
  - python setup.py bdist_wheel
  - python setup.py bdist_wininst
  - python setup.py bdist_msi
  - ps: "ls dist"

  # create one-file executable
  - pyinstaller --onefile --clean --name cbsh --hidden-import "cookiecutter.extensions" --hidden-import "jinja2_time" --hidden-import "sphinx.util.compat" --hidden-import "sphinxcontrib.xbr" cbsh/cli.py
  - ps: "ls dist"
  - cmd: dist\cbsh.exe version


#  twine upload dist/*

# Directory: C:\projects\crossbar-shell\dist
# Mode                LastWriteTime         Length Name                                                                                                                                                                                
# ----                -------------         ------ ----                                                                                                                                                                                
# -a----        4/13/2018   9:44 AM          49490 cbsh-18.4.6-py2.py3-none-any.whl                                                                                                                                                    
# -a----        4/13/2018   9:44 AM         548439 cbsh-18.4.6.win32.exe                                                                                                                                                               
# -a----        4/13/2018   9:44 AM         204800 cbsh-18.4.6.win32.msi                   


# C:\Users\crossbar\Documents\GitHub\crossbario\crossbar-shell>pyinstaller --onefile --clean --name cbsh --hidden-import "cookiecutter.extensions" --hidden-import "jinja2_time" --hidden-import "sphinx.util.compat" --hidden-import "sphinxcontrib.xbr" cbsh/cli.py

#artifacts:
#  # Archive the generated packages in the ci.appveyor.com build report.
#  - path: dist\*

#on_success:
#  - TODO: upload the content of dist/*.whl to a public wheelhouse
#
