language: python

sudo: false

install:
  - pip install tox
#  - pip install tox codecov

script:
  - tox -c tox.ini -e $TOX_ENV

#after_success:
#  # since we use --parallel-mode to coverage inside Tox we use
#  # "coverage combine" so the filename is always ".coverage"
#  - cd test && coverage combine && codecov

matrix:
  fast_finish: true

  # https://github.com/travis-ci/travis-ci/issues/4794#issuecomment-143758799
  include:
    - env: TOX_ENV=flake8

    - python: 3.6
      env:
      - TOX_ENV=py36

notifications:
   irc:
      channels:
         - "irc.freenode.org#autobahn"
      use_notice: true
      skip_join: true
